import 'package:flutter/material.dart';

const Color pKcolor = Color(0xff1E2A5E);
const Color scColor = Color(0xff5A5A5A);
const Color blackColor = Color(0xff240301);
const String token = "token";
const String notifChannelKey = "basic_channel";
const String baseUrl = "";
const String kUserDetails = "UserDetails";
const String kSand1Price = "بصرى";
const String kSand2Price = "عادية";

const String kGravel1Price = "عادى ";
const String kGravel2Price = "سن";
const String kBlockPrice = "blockPrice";
const String kBlockNumber = "BlockNumber";
const String kExpensesItem = "ExpensesItem";
const String kExpensesModel = "ExpensesModel";
const String kWorkPrice = "WorkPrice";
const String kAccountExport = "AccountExport";
const String kAccountImport = "AccountImport";
const String kAccountTotal = "AccountTotal";
const String kImportStoreItem = "ImportStoreItem";
const String kImportStoreBill = "ImportStoreBill";
const String kStoreItemBasket = "StoreItemBasket";
const String kInventoryStoreItem = "InventoryStoreItem";
const String kImportM7jarBill = "ImportM7jarBill";
const String kImportBlockBill = "ImportBlockBill";
const String kExportStoreBill = "ExportStoreBill";
const String kHistory = "History";
const String kSupplierModel = "SupplierModel";
const String kSupplierTable = "Suppliers";
const String kCustomerTable = "customers";
const String kEmployeeTable = "employees";
const String kInventoryTable = "inventory";
const String kCategoryTable = "Categories";
const String kTransactionTable = "transactions";
